### ISSUE TITLE
Mongo Integration

### ISSUE THREAD

**Issue by dalexj** [nii236/nii-finance#1]
does this work with mongo?

**Comment by nii236** [comment]
Hey @dalexj, there's no allowance for MongoDB at the moment. I figured columnar databases such as Prometheus, Influx or TSDB are more suitable due to ticker data's consistent schemas and being a time series.

That said, since the tick data is being published on a message queue, its not a problem to write another microservice that also subscribes to the tick streaming queue and then write records into MongoDB.
